version: "3"
services:
  app:
    build:
      context: ./app
    volumes:
      - app-build:/app/build
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 8192M
    depends_on:
      - api

  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - REMEMBER_ME_COOKIE_NAME=${REMEMBER_ME_COOKIE_NAME}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      - redis
      - db

  dashboard:
    build:
      context: ./dashboard
    volumes:
      - dashboard-build:/dashboard/build
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 8192M
    depends_on:
      - dashboard-api

  dashboard-api:
    build:
      context: ./dashboard-api
    ports:
      - "4001:4001"
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - REMEMBER_ME_COOKIE_NAME=${REMEMBER_ME_COOKIE_NAME}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      - redis
      - db

  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
      - ./keys:/etc/mysql/encryption
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306" # remove this line in production!
    command: --event_scheduler=ON --max-allowed-packet=128MB --plugin-load-add=file_key_management --loose_file_key_management_filename=/etc/mysql/encryption/keyfile --file-key-management=FORCE

  adminer: # remove this in production!
    profiles: ["dev"]
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  caddy:
    build:
      context: ./caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app-build:/srv
      - dashboard-build:/srv-dashboard
    depends_on:
      - api
      - app
      - dashboard
      - dashboard-api

volumes:
  redis-data:

  app-build:

  dashboard-build:

  db-data:
