version: "3"
services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    volumes:
      - app-build:/app/build
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192

  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - REMEMBER_ME_COOKIE_NAME=${REMEMBER_ME_COOKIE_NAME}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}

  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306" # remove this line in production!
    command: --event_scheduler=ON

  adminer:
    image: adminer
    ports:
      - 8080:8080

  caddy:
    build:
      context: ./caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app-build:/srv

volumes:
  redis-data:

  app-build:
