version: "3"
services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
    ports:
      - "4000:4000"


  db:
    image: mariadb:10.6
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
