version: "3"
services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  db:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8080:8080
